---
- name: create directories if they don't exist
  # become: yes
  #become_user: dbops
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - /data/cassandra/data
    - /data/cassandra/saved_caches
    - /data/cassandra/hints
    - /data/cassandra/commitlog
    - /var/log/cassandra
    - /var/run/cassandra
  tags: always
