---

- hosts: all
  gather_facts: false
  serial: 1
#  vars:
#   rackdc_file_path: /home/cassandra/DSE_INSTALL/dse-6.8.23/resources/cassandra/conf/cassandra-rackdc.properties
#   conf_file_path: /home/cassandra/DSE_INSTALL/dse-6.8.23/resources/cassandra/conf/cassandra.yaml

  tasks:
   - name: Check CPU_CORE
     shell: lscpu | grep "Core"
     register: core

   - name: Print Core
     debug:
      msg: "{{core.stdout}}"

   - name: create file to add nodename to it
     become: yes
     become_user: acassandra
     blockinfile:
      path: /apps/cassandra/pooja.nair_playbooks/adhoc_scripts/core_file
      block: |
       "{{inventory_hostname}}"
       "{{core.stdout}}"
      marker: ""
      create: yes
     delegate_to: 127.0.0.1


