---

- hosts: all
  gather_facts: false
  serial: 1

  tasks:
   - name: Check CPU_CORE
     shell: netstat -na | grep 9042 | wc -l
     register: connection

   - name: Print Core
     debug:
      msg: "{{connection.stdout}}"

   - name: create file to add nodename to it
     become: yes
     become_user: acassandra
     blockinfile:
      path: /apps/cassandra/pooja.nair_playbooks/adhoc_scripts/core_file
      block: |
       "{{inventory_hostname}}"
       "{{connection.stdout}}"
      marker: ""
      create: yes
     delegate_to: 127.0.0.1

