---

- hosts: all
  gather_facts: false
  serial: 1
#  vars:
#   rackdc_file_path: /home/cassandra/DSE_INSTALL/dse-6.8.23/resources/cassandra/conf/cassandra-rackdc.properties
#   conf_file_path: /home/cassandra/DSE_INSTALL/dse-6.8.23/resources/cassandra/conf/cassandra.yaml

  tasks:
   - name: Check memory
     shell: free -g
     register: mem

   - name: Print memory
     debug:
      msg: "{{inventory_hostname}}"

   - name: create file to add nodename to it
     blockinfile:
      path: ./mem_file
      block: |
       "{{inventory_hostname}}"
       "{{mem.stdout}}"
      marker: ""
      create: yes
     delegate_to: 127.0.0.1
