# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

# User specific environment and startup programs

# Set the JAVA_HOME path
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre

# Set Cassandra environment variables
export CASSANDRA_HOME=/opt/apache-cassandra-4.0.14
export CASSANDRA_CONF=$CASSANDRA_HOME/conf
export CASSANDRA_LOG=$CASSANDRA_HOME/logs/system.log

# Update PATH to include Java and Cassandra binaries
export PATH=$JAVA_HOME/bin:$CASSANDRA_HOME/bin:$HOME/bin:$PATH

# Set CLASSPATH
export CLASSPATH=$JAVA_HOME:$JAVA_HOME/lib:$JAVA_HOME/jre/lib:$JAVA_HOME/jre/lib/ext:$CASSANDRA_HOME/lib:$CASSANDRA_CONF:.

# Set aliases for ease of operation

alias casslog='tail -100f $CASSANDRA_LOG'

